version: '3'
services:
  nginx:
    container_name: "nginx"
    build: ./nginx
    volumes:
      - ./website/bedrock:/var/www/html
    ports:
        - "80:80"
    restart: always
    depends_on:
      - php
      - mariadb
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    ports:
        - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: mariadb
    restart: always
    depends_on:
      - mariadb
  php:
    container_name: "php"
    build: ./website
    env_file: ./website/env/.env.dev
    volumes:
      - ./website/bedrock:/var/www/html
  mariadb:
    container_name: "mariadb"
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
